os: osx
osx_image: xcode9.2
language: objective-c
cache:
  directories:
    - Carthage/
install:
  - carthage update --platform $CARTHAGE
before_script: 
  - swiftlint
matrix:
  include:
    - env: PLATFORM=macOS DESTINATION='platform=macOS,arch=x86_64' CARTHAGE=$PLATFORM
    - env: PLATFORM=iOS DESTINATION='platform=iOS Simulator,name=iPhone 8' CARTHAGE=iOS,watchOS
    - env: PLATFORM=tvOS DESTINATION='platform=tvOS Simulator,name=Apple TV' CARTHAGE=$PLATFORM
    - env: PLATFORM=watchOS CARTHAGE=iOS,watchOS
script:
  - ./scripts/run_tests
