os: osx
osx_image: xcode9.2
language: objective-c
cache:
  directories:
    - Carthage/
install:
  - carthage update --platform $PLATFORM
before_script: 
  - swiftlint
matrix:
  include:
    - env: PLATFORM=macOS DESTINATION='platform=macOS,arch=x86_64'
    - env: PLATFORM=iOS DESTINATION='platform=iOS Simulator,name=iPhone 6'
script:
  - xcodebuild -project RxSpriteKit.xcodeproj -scheme RxSpriteKitDemo-$PLATFORM -destination '${DESTINATION}'
